name: ci

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug 
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUP: toae
      COMMIT: ${{ github.sha }}
      REPO: demo-app
    steps:
    - uses: actions/checkout@v2

    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v1
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    # Run Toae YaRadare scans to find indicators of malware in container images.
    - name: Run Toae YaRadare scans 
      env:
        FULL_IMAGE_NAME: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}
      run: |
        docker pull toaeio/toae-yaradare:latest
        docker run --rm --name=toae-yaradare -v /var/run/docker.sock:/var/run/docker.sock toaeio/toae-yaradare:latest --image-name $FULL_IMAGE_NAME