node {
    def app
    def full_image_name = 'toaeio/jenkins-example:latest'

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        app = docker.build("${full_image_name}", "-f ci-cd-integration/jenkins/Dockerfile .")
    }

    stage('Run Toae YaRadare'){
        ToaeAgent = docker.image("toaeio/toae-yaradare:latest")
        try {
            c = ToaeAgent.run("--rm --name=toae-yaradare -v /var/run/docker.sock:/var/run/docker.sock", "--image-name ${full_image_name}")
            sh "docker logs -f ${c.id}"
            def out = sh script: "docker inspect ${c.id} --format='{{.State.ExitCode}}'", returnStdout: true
            sh "exit ${out}"
        } finally {
            c.stop()
        }
    }

    stage('Remove unused docker image') {
        sh "docker rmi ${full_image_name}"
    }
}